### ISSUE TITLE
problem since mootools 1.4.4 update

### ISSUE THREAD

**Issue by gingebaker** [ryanflorence/SlideShow#12]
Hello
Does anyone also experience problems when trying to run the slideshow with mootools core 1.4.4? In special the "pushLeft" and pushRight" effect does not work properly. It slides only the current image away. The second image transition does not play...

I tested it with mootools 1.4.3: Here it is working again. So the problem has to be in one of the last mootools core changes?

http://mootools.net/blog/

regards, tom

**Comment by arian** [comment]
It's a problem with 1.4.4. A new MooTools release will be released very soon. Until then please use 1.4.3 or another version.

**Comment by gingebaker** [comment]
Thanks for the reply!! I will do that...
